owner: masslight 
repo: upptime 

sites:
  - name: Homepage
    url: https://www.zapehr.com
  - name: Documentation
    url: https://docs.zapehr.com
  - name: Console
    url: https://console.zapehr.com
  - name: FHIR API
    url: https://fhir-api.zapehr.com/version
  - name: Platform API
    url: https://platform-api.zapehr.com/v1/version
  - name: Project API
    url: https://project-api.zapehr.com/v1/version
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co
  - name: IPv6 test
    url: forwardemail.net
    port: 80
    check: "tcp-ping"
    ipv6: true
  

assignees:
  - GiladSchneider

status-website:
  # cname: demo.upptime.js.org
  name: ZapEHR Status
  baseUrl: /upptime
  logoUrl: https://zapehr-public-files.s3.amazonaws.com/favicon.png
  favicon: https://zapehr-public-files.s3.amazonaws.com/favicon.png
  themeUrl: https://masslight.github.io/upptime/zapehr-theme.css
  navbar:
    - title: Status
      href: /
    - title: Homepage
      href: https://zapehr.com
    - title: Documentation
      href: https://docs.zapehr.com
