owner: masslight 
repo: upptime 

sites:
  - name: Homepage
    url: https://www.oystehr.com    
  - name: Documentation
    url: https://docs.oystehr.com
  - name: API Reference
    url: https://api-reference.oystehr.com
  - name: Console
    url: https://console.oystehr.com
  - name: FHIR API
    url: https://fhir-api.zapehr.com/version
    icon: https://zapehr-public-files.s3.amazonaws.com/oystehr-favicon.png
  - name: Platform API
    url: https://platform-api.zapehr.com/v1/version
    icon: https://zapehr-public-files.s3.amazonaws.com/oystehr-favicon.png
  - name: Project API
    url: https://project-api.zapehr.com/v1/version
    icon: https://zapehr-public-files.s3.amazonaws.com/oystehr-favicon.png
    
assignees:
  - GiladSchneider

status-website:
  name: Status
  cname: status.oystehr.com
  logoUrl: https://zapehr-public-files.s3.amazonaws.com/oystehr-logo-white.svg
  favicon: https://zapehr-public-files.s3.amazonaws.com/oystehr-favicon.png
  themeUrl: https://status.oystehr.com/zapehr-theme.css
  navbar:
    - title: Homepage
      href: https://oystehr.com
    - title: Documentation
      href: https://docs.oystehr.com
