owner: masslight 
repo: upptime 

sites:
  - name: ZapEHR
    url: https://www.zapehr.com
  - name: Google
    url: https://www.google.com
  - name: Wikipedia
    url: https://en.wikipedia.org
  - name: Hacker News
    url: https://news.ycombinator.com
  - name: Test Broken Site
    url: https://thissitedoesnotexist.koj.co

assignees:
  - GiladSchneider

status-website:
  # cname: demo.upptime.js.org
  name: ZapEHR Status
  baseUrl: /upptime
  logoUrl: https://zapehr-public-files.s3.amazonaws.com/favicon.png
  favicon: https://zapehr-public-files.s3.amazonaws.com/favicon.png
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
